import React from 'react';
import { Link } from 'react-router-dom';
import { PageShell } from '../components/layout/PageShell';
import { DisclaimerBanner } from '../components/layout/DisclaimerBanner';
import { Button } from '../components/ui/Button';
import { SeverityBadge } from '../components/ui/SeverityBadge';
import { useHistory } from '../hooks/useHistory';
import { api } from '../lib/api';
import {
  FileText,
  Download,
  CheckCircle2,
  FileCheck,
  Search,
} from 'lucide-react';

export const Reports: React.FC = () => {
  const { records } = useHistory();

  const handleDownloadPdf = async (analysisId: string) => {
    try {
      const blob = await api.downloadReport(analysisId);
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `civisight_report_${analysisId.slice(0, 8)}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch {
      alert('Could not download PDF. The analysis files may have expired on the server.');
    }
  };

  return (
    <PageShell title="Inspection Reports">
      <div className="space-y-8 py-6 px-4 sm:px-6 max-w-screen-xl mx-auto">
        <DisclaimerBanner />

        {/* Header */}
        <div>
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight flex items-center gap-2">
            <FileText className="w-6 h-6 text-brand" />
            Inspection Reports
          </h1>
          <p className="text-sm text-slate-600 mt-1">
            Generate and export auditable PDF inspection documentation.
          </p>
        </div>

        {/* Report Features Explanation Card */}
        <div className="bg-surface p-6 rounded-2xl border border-border space-y-4">
          <h2 className="text-base font-bold text-slate-900 flex items-center gap-2">
            <FileCheck className="w-5 h-5 text-brand" />
            Standard CiviSight Engineering Report Structure
          </h2>
          <p className="text-xs text-slate-600 leading-relaxed">
            Every inspection report generated by CiviSight AI is produced deterministically on the backend via ReportLab and includes:
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3 text-xs">
            <div className="flex items-start gap-2 p-2.5 rounded-lg bg-slate-50 border border-slate-200">
              <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
              <div>
                <strong className="text-slate-800 block">Metadata & Timestamps</strong>
                <span className="text-slate-500">Inspection ID, date, module, and compute model.</span>
              </div>
            </div>
            <div className="flex items-start gap-2 p-2.5 rounded-lg bg-slate-50 border border-slate-200">
              <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
              <div>
                <strong className="text-slate-800 block">Prominent Disclaimer</strong>
                <span className="text-slate-500">Verbatim statement on preliminary visual scope.</span>
              </div>
            </div>
            <div className="flex items-start gap-2 p-2.5 rounded-lg bg-slate-50 border border-slate-200">
              <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
              <div>
                <strong className="text-slate-800 block">Original & Annotated Imagery</strong>
                <span className="text-slate-500">Side-by-side or stacked visual evidence.</span>
              </div>
            </div>
            <div className="flex items-start gap-2 p-2.5 rounded-lg bg-slate-50 border border-slate-200">
              <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
              <div>
                <strong className="text-slate-800 block">Condition Indicator (0–100)</strong>
                <span className="text-slate-500">Mathematical breakdown with penalty factors.</span>
              </div>
            </div>
            <div className="flex items-start gap-2 p-2.5 rounded-lg bg-slate-50 border border-slate-200">
              <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
              <div>
                <strong className="text-slate-800 block">Findings & Severity Table</strong>
                <span className="text-slate-500">Numbered targets, area %, grid location, score.</span>
              </div>
            </div>
            <div className="flex items-start gap-2 p-2.5 rounded-lg bg-slate-50 border border-slate-200">
              <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
              <div>
                <strong className="text-slate-800 block">Deterministic Guidance</strong>
                <span className="text-slate-500">Rule-based recommendations and limitations list.</span>
              </div>
            </div>
          </div>
        </div>

        {/* Available Reports Table */}
        <div className="space-y-4">
          <h2 className="text-lg font-bold text-slate-900">
            Available Reports ({records.length})
          </h2>

          {records.length === 0 ? (
            <div className="text-center py-16 bg-surface rounded-2xl border border-border space-y-3">
              <Search className="w-10 h-10 text-slate-300 mx-auto" />
              <h3 className="text-base font-semibold text-slate-800">No reports generated yet</h3>
              <p className="text-xs text-slate-500 max-w-sm mx-auto">
                Run an inspection to create a downloadable, professional PDF report.
              </p>
              <div className="pt-2">
                <Link to="/inspect/crack_detection">
                  <Button variant="primary" size="sm">
                    Start Inspection
                  </Button>
                </Link>
              </div>
            </div>
          ) : (
            <div className="bg-surface rounded-xl border border-border overflow-hidden">
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs">
                  <thead className="bg-slate-50 border-b border-border text-slate-muted uppercase font-medium">
                    <tr>
                      <th className="py-3 px-4">Inspection</th>
                      <th className="py-3 px-4">Date / Time</th>
                      <th className="py-3 px-4">Module</th>
                      <th className="py-3 px-4">Severity</th>
                      <th className="py-3 px-4">Findings</th>
                      <th className="py-3 px-4 text-right">Download</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-border">
                    {records.map((r) => (
                      <tr key={r.analysis_id} className="hover:bg-slate-50 transition-colors">
                        <td className="py-2.5 px-4 font-mono font-medium text-slate-900">
                          #{r.analysis_id.slice(0, 8)}
                        </td>
                        <td className="py-2.5 px-4 text-slate-500 font-mono">
                          {new Date(r.created_at).toLocaleString()}
                        </td>
                        <td className="py-2.5 px-4 capitalize font-medium text-slate-700">
                          {r.inspection_type.replace('_', ' ')}
                        </td>
                        <td className="py-2.5 px-4">
                          {r.overall_severity ? (
                            <SeverityBadge severity={r.overall_severity} size="sm" />
                          ) : (
                            <span className="text-slate-400">—</span>
                          )}
                        </td>
                        <td className="py-2.5 px-4 font-mono text-slate-700">
                          {r.total_detections}
                        </td>
                        <td className="py-2.5 px-4 text-right">
                          <Button
                            variant="outline"
                            size="sm"
                            leftIcon={<Download className="w-3.5 h-3.5" />}
                            onClick={() => handleDownloadPdf(r.analysis_id)}
                          >
                            PDF
                          </Button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>
      </div>
    </PageShell>
  );
};
