"""
Civil engineering visual triage thresholds and configuration constants.
As noted in PRD Section 11, these are heuristic visual-triage thresholds chosen
for this academic prototype and are not code-based engineering criteria.
"""

# Classical Crack Baseline Thresholds
CLASSICAL_CRACK_MAX_DIM = 1280
CLASSICAL_CRACK_CLAHE_CLIP = 2.0
CLASSICAL_CRACK_CLAHE_GRID = (8, 8)
CLASSICAL_CRACK_SATO_SIGMAS = [1.5, 2.5, 3.5]
CLASSICAL_CRACK_PERCENTILE = 99.5
CLASSICAL_CRACK_HYSTERESIS_LOW = 0.25
CLASSICAL_CRACK_HYSTERESIS_HIGH = 0.50
CLASSICAL_CRACK_MIN_AREA_RATIO = 0.00015
CLASSICAL_CRACK_MIN_LENGTH_RATIO = 0.04
CLASSICAL_CRACK_MAX_WIDTH_RATIO = 0.02
CLASSICAL_CRACK_TEXTURE_GUARD_RATIO = 0.12
CLASSICAL_CRACK_LENGTH_NORM_RATIO = 0.15

# Crack Severity Thresholds
CRACK_HIGH_LENGTH_RATIO = 0.40
CRACK_HIGH_AREA_RATIO = 0.04
CRACK_MODERATE_LENGTH_RATIO = 0.15
CRACK_MODERATE_AREA_RATIO = 0.01

CRACK_ESCALATE_COUNT_LOW_TO_MOD = 5
CRACK_ESCALATE_MIN_SCORE = 0.50
CRACK_ESCALATE_COUNT_TO_HIGH = 3

# Pothole Severity Thresholds
POTHOLE_HIGH_AREA_RATIO = 0.06
POTHOLE_MODERATE_AREA_RATIO = 0.015

POTHOLE_ESCALATE_COUNT_TO_MOD = 3
POTHOLE_ESCALATE_COUNT_TO_HIGH = 3

# Safety Thresholds
SAFETY_ASSESSABLE_MIN_HEIGHT_RATIO = 0.04
SAFETY_HEAD_REGION_X_TOLERANCE = 0.10  # +-10% person width
SAFETY_HEAD_REGION_Y_TOP_OFFSET = 0.10   # y1 - 0.10*h
SAFETY_HEAD_REGION_Y_BOTTOM_OFFSET = 0.40  # y1 + 0.40*h

SAFETY_COMPLIANCE_HIGH_THRESHOLD = 75.0   # < 75% -> high
SAFETY_COMPLIANCE_FULL_THRESHOLD = 100.0  # 100% -> low; [75%, 100%) -> moderate

# Condition Indicator (defect_v1)
CONDITION_WEIGHTS = {
    "low": 4,
    "moderate": 10,
    "high": 18,
}
CONDITION_MAX_FINDING_PENALTY = 60.0
CONDITION_MAX_AREA_PENALTY = 25.0
CONDITION_AREA_MULTIPLIER = 150.0

# Condition Indicator Bands
CONDITION_BAND_GREEN_MIN = 80
CONDITION_BAND_AMBER_MIN = 50

# General Confidence Tagging
LOW_CONFIDENCE_THRESHOLD = 0.50
